version: "3"

services:
  web:
    image: "${LANDSCAPING_IMAGE}"
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py loaddata dumps/*.json || true && python -u manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/landscaping
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - db

  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "landscaping"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  .:
  postgres_data: