# Generated by Django 3.1.3 on 2020-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='workers',
            field=models.ManyToManyField(blank=True, to='core.Worker', verbose_name='actions'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='residents', to='core.Resident'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='workers',
            field=models.ManyToManyField(blank=True, to='core.Worker', verbose_name='workers'),
        ),
    ]
